### ISSUE TITLE
databaseTable values are not respected when launching a shiny app

### ISSUE THREAD

**Issue by DrTTrousers** [OHDSI/ShinyAppBuilder#19]
https://github.com/OHDSI/ShinyAppBuilder/blob/2f3cf46e6ab7e5cb1b242bfa5da36ea234e59fe9/R/ViewShiny.R#L48C8-L48C8

This line forces the shiny app by default to look in the wrong table name as configured in the defaultModuleConfig functions, resulting in app launching but data not loading.

To remedy, either update the default in this argument to the default module config option (and RMM option) or leave the argument blank to force the user to update it manually.

Currently, the code fails silently and it is quite hard to track down!

**Comment by jreps** [comment]
Thanks for finding this - I just made a commit that uses the default function:
resultDatabaseSettings = createDefaultResultDatabaseSettings()

I also set this in viewShiny for consistency.

Hopefully this fixes the issue?

**Comment by DrTTrousers** [comment]
Looks to be good now!
